In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from time import sleep
from random import randint

In [2]:
headers={"Accept-Language":"en-US,en;,q=0.5"}

In [3]:
movie_name = []
year = []
time=[]
rating=[]
metascore =[]
votes = []
gross = []

In [4]:
pages=np.arange(1,1000,50)

In [5]:
print(pages)

[  1  51 101 151 201 251 301 351 401 451 501 551 601 651 701 751 801 851
 901 951]

In [6]:
for page in pages:
    page=requests.get("https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=50&start="+str(page)+"&ref_=adv_nxt")
    soup=BeautifulSoup(page.text,'html.parser')   
    movie_data=soup.findAll('div',attrs={'class':'lister-item mode-advanced'})
    sleep(randint(2,8))
    for store in movie_data:
        name=store.h3.a.text
        movie_name.append(name)
        
        year_of_release=store.h3.find('span', class_="lister-item-year text-muted unbold").text
        year.append(year_of_release)
        
        
        runtime=store.p.find("span",class_='runtime').text
        time.append(runtime)
        
        
        rate=store.find('div',class_="inline-block ratings-imdb-rating").text
        rating.append(rate)
        
        meta=store.find('span',class_="metascore").text if store.find('span',class_="metascore") else "*******"
        metascore.append(meta)
        
        value=store.find_all('span', attrs={'name':"nv"})
        
        vote=value[0].text
        votes.append(vote)
        
        grosses=value[1].text if len(value)>1 else '%%%%%%'
        gross.append(grosses)
        
movie_list = pd.DataFrame({ "Movie Name": movie_name, "Year of Release" : year, "Watch Time": time,"Movie Rating": rating, "Meatscore of movie": metascore, "Votes" : votes, "Gross": gross })

In [7]:
movie_list

,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross
0,The Shawshank Redemption,(1994),142 min,\n\n9.3\n,81,"2,634,000",$28.34M
1,The Godfather,(1972),175 min,\n\n9.2\n,100,"1,825,499",$134.97M
2,Rocketry: The Nambi Effect,(2022),157 min,\n\n9.0\n,*******,"41,902",%%%%%%
3,The Dark Knight,(2008),152 min,\n\n9.0\n,84,"2,605,270",$534.86M
4,The Lord of the Rings: The Return of the King,(2003),201 min,\n\n9.0\n,94,"1,806,905",$377.85M
...,...,...,...,...,...,...,...
995,Sabrina,(1954),113 min,\n\n7.6\n,72,"65,004",%%%%%%
996,From Here to Eternity,(1953),118 min,\n\n7.6\n,85,"47,094",$30.50M
997,Snow White and the Seven Dwarfs,(1937),83 min,\n\n7.6\n,95,"198,031",$184.93M
998,The 39 Steps,(1935),86 min,\n\n7.6\n,93,"56,998",%%%%%%
999,The Invisible Man,(1933),71 min,\n\n7.6\n,87,"34,960",%%%%%%

In [9]:
movie_list.head(10)

,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross
0,The Shawshank Redemption,(1994),142 min,\n\n9.3\n,81,"2,634,000",$28.34M
1,The Godfather,(1972),175 min,\n\n9.2\n,100,"1,825,499",$134.97M
2,Rocketry: The Nambi Effect,(2022),157 min,\n\n9.0\n,*******,"41,902",%%%%%%
3,The Dark Knight,(2008),152 min,\n\n9.0\n,84,"2,605,270",$534.86M
4,The Lord of the Rings: The Return of the King,(2003),201 min,\n\n9.0\n,94,"1,806,905",$377.85M
5,Schindler's List,(1993),195 min,\n\n9.0\n,94,"1,336,241",$96.90M
6,The Godfather Part II,(1974),202 min,\n\n9.0\n,90,"1,252,152",$57.30M
7,12 Angry Men,(1957),96 min,\n\n9.0\n,96,"777,811",$4.36M
8,Jai Bhim,(2021),164 min,\n\n8.9\n,*******,"196,899",#245
9,Pulp Fiction,(1994),154 min,\n\n8.9\n,94,"2,016,090",$107.93M

In [2]:
movie_list.head(15)

NameError: name 'movie_list' is not defined